# 시작 명령어
# docker-compose -f docker-compose.prod.yml up -d

version: "3.9"

services:
  app:
    image: ${DOCKER_USERNAME}/caro-server:latest
    container_name: caro-app
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=mysql-container
      - REDIS_HOST=redis-container
      - JWT_SECRET=${JWT_SECRET}
      - DDL_AUTO=${DDL_AUTO:-validate}
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - caro-net

  mysql:
    image: mysql:8.0.34
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: caro_db
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - caro-net

  redis:
    image: redis:7.2.0
    container_name: redis-container
    volumes:
      - redis-data:/data
    networks:
      - caro-net

networks:
  caro-net:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
