# 시작 명령어
# docker-compose -f docker-compose.dev.yml up -d

version: "3.9"

services:
  app:
    image: ${DOCKER_USERNAME}/caro-server:latest
    container_name: caro-app
    ports:
      - "${APP_PORT}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=mysql-container
      - REDIS_HOST=redis-container
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mysql
      - redis
    networks:
      - caro-net

  mysql:
    image: mysql:8.0.34
    container_name: mysql-container
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: caro_db
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - caro-net

  redis:
    image: redis:7.2.0
    container_name: redis-container
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    networks:
      - caro-net

networks:
  caro-net:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
