spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql-container}:3306/caro_db?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      jdbc:
        time_zone: Asia/Seoul
    show-sql: false
  flyway:
    enabled: true
    clean-disabled: true
  data:
    redis:
      host: ${REDIS_HOST:redis-container}
      port: 6379

server:
  port: ${APP_PORT:8080}

api:
  server:
    url: https://api.caro.today
  cors:
    allowed-origins: http://localhost:8081,https://caro.today,https://api.caro.today,https://caro-frontend-sigma.vercel.app

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 1800000
  refresh-token-expiration: 1209600000

logging:
  level:
    root: INFO
