spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql-container}:3306/caro_db?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
    show-sql: false
  data:
    redis:
      host: ${REDIS_HOST:redis-container}
      port: 6379

server:
  port: ${APP_PORT:8080}

api:
  server:
    url: https://api.caro.today

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 1800000
  refresh-token-expiration: 1209600000

logging:
  level:
    root: INFO
